name: build

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check code
        run: make check

      - name: Unit tests
        run: make test
  
      