name: code-quality

on: [pull_request]

jobs: 
    code_compile:
        runs-on: ubuntu-latest
        name: Code Compile Job
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - run: cargo check

    format_code:
        runs-on: ubuntu-latest
        name: Format Code Job

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                sudo apt-get install python3-pip
                pip install black

            - name: Use Black
              run: black tests

            - run: cargo fmt --check





    schema:
        runs-on: ubuntu-latest
        name: Verify Schema Job
        steps:
            - run: cargo clippy

            