name: Close PR

on:
  #pull_request_target:
    #types: [ opened ]

  pull_request:
    branches: [ "release" ]
permissions:
  write-all

jobs:
  close_pr:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref != 'main' || github.base_ref != 'bug/*' }}
    steps:
      - name: Close PR
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "We do not accept PRs. If you have any questions, please feel free to contact us."

  debug_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}




